name: CI

# Controla quando o fluxo de trabalho será executado
on:
  # Aciona o fluxo de trabalho ao fazer push ou pull request para a branch master
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Permite executar este fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Um fluxo de trabalho é composto por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único job chamado "test-lint"
  test-lint:
  
    # O tipo de runner em que o job será executado
    runs-on: ubuntu-latest

    # Os steps representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Faz o checkout do seu repositório em $GITHUB_WORKSPACE, para que o job possa acessá-lo
      - name: Checkout do código
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            CI_CD:
              - 'ci_cd/**' 

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
        
      - name: Instalar Just
        uses: extractions/setup-just@v1

      # Verifica a estrutura do repositório após o checkout para garantir que os arquivos estão no lugar correto
      - name: Verificar estrutura do repositório (debug)
        run: ls -R

      # Instala as dependências do projeto usando Poetry dentro da pasta 'ci_cd'
      - name: Instalar dependências
        run: poetry install
        working-directory: ci_cd  # Define o diretório correto

      # Executa o lint para verificar a qualidade do código dentro da pasta 'ci_cd'
      - name: lint
        run: just lint
        working-directory: ci_cd  # Define o diretório correto

      # Executa os testes do projeto dentro da pasta 'ci_cd'
      - name: testes
        run: just teste
        working-directory: ci_cd  # Define o diretório correto

      - name: testes
        run: just teste
